import type { Metadata } from "next";
import { Quicksand } from 'next/font/google';  // Add this import
import "./globals.css";

// Replace the Geist fonts with Quicksand
const quicksand = Quicksand({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-quicksand',  // Add a variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}